exports.postRoutes = require('./postRoutes')
exports.getRoutes  = require('./getRoutes')
exports.protectedRoutes  = require('./protectedRoutes')
exports.adminRoutes = require("./adminRoutes")
exports.userRoutes = require("./userRoutes")